export enum SYSTEM_SERVICE_EVENTS {
    CONFIGURATION_LOADED = "CONFIGURATION_LOADED"
}

export enum CONFIGURATION_SERVICE_EVENTS {
    CONFIGURATION_CHANGED = "CONFIGURATION_CHANGED",
    CONFIGURATION_LOADED = "CONFIGURATION_LOADED"
}