import {TableNames} from '../enums/Database';

let baseRoleValues = [{
       [TableNames.Role_base.id]: 1,
       [TableNames.Role_base.role_name]: "SuperAdmin",
       [TableNames.Role_base.auth_login]: true,
       [TableNames.Role_base.auth_change_password]: false,
       [TableNames.Role_base.admin_add]: true,
       [TableNames.Role_base.admin_update]: true,
       [TableNames.Role_base.admin_remove]: true,
       [TableNames.Role_base.admin_search]: true,
       [TableNames.Role_base.data_export]: true,
       [TableNames.Role_base.data_import]: true,
       [TableNames.Role_base.client_incorporate]: false,
       [TableNames.Role_base.client_udpate]: false,
       [TableNames.Role_base.client_desincorporate]: false,
       [TableNames.Role_base.client_search]: true,
       [TableNames.Role_base.payment_add]: false,
       [TableNames.Role_base.payment_search]: false,
       [TableNames.Role_base.payment_update]: false,
       [TableNames.Role_base.payment_remove]: false,
       [TableNames.Role_base.role_update]: true,
       [TableNames.Role_base.status]: 1,
       [TableNames.Role_base.version]: 1
},{
       [TableNames.Role_base.id]: 2,
       [TableNames.Role_base.role_name]: "Admin",
       [TableNames.Role_base.auth_login]: true,
       [TableNames.Role_base.auth_change_password]: true,
       [TableNames.Role_base.admin_add]: false,
       [TableNames.Role_base.admin_update]: false,
       [TableNames.Role_base.admin_remove]: false,
       [TableNames.Role_base.admin_search]: false,
       [TableNames.Role_base.data_export]: false,
       [TableNames.Role_base.data_import]: false,
       [TableNames.Role_base.client_incorporate]: true,
       [TableNames.Role_base.client_udpate]: true,
       [TableNames.Role_base.client_desincorporate]: true,
       [TableNames.Role_base.client_search]: true,
       [TableNames.Role_base.payment_add]: true,
       [TableNames.Role_base.payment_search]: true,
       [TableNames.Role_base.payment_update]: true,
       [TableNames.Role_base.payment_remove]: false,
       [TableNames.Role_base.role_update]: false,
       [TableNames.Role_base.status]: 1,
       [TableNames.Role_base.version]: 1
},{
       [TableNames.Role_base.id]: 3,
       [TableNames.Role_base.role_name]: "Cliente",
       [TableNames.Role_base.auth_login]: false,
       [TableNames.Role_base.auth_change_password]: false,
       [TableNames.Role_base.admin_add]: false,
       [TableNames.Role_base.admin_update]: false,
       [TableNames.Role_base.admin_remove]: false,
       [TableNames.Role_base.admin_search]: false,
       [TableNames.Role_base.data_export]: false,
       [TableNames.Role_base.data_import]: false,
       [TableNames.Role_base.client_incorporate]: false,
       [TableNames.Role_base.client_udpate]: false,
       [TableNames.Role_base.client_desincorporate]: false,
       [TableNames.Role_base.client_search]: false,
       [TableNames.Role_base.payment_add]: false,
       [TableNames.Role_base.payment_search]: false,
       [TableNames.Role_base.payment_update]: false,
       [TableNames.Role_base.payment_remove]: false,
       [TableNames.Role_base.role_update]: false,
       [TableNames.Role_base.status]: 1,
       [TableNames.Role_base.version]: 1
}];
export const BaseRoles = baseRoleValues;